### ISSUE TITLE
parser_utils.cc.o error during build

### ISSUE THREAD

**Issue by mfs4rd** [google/draco#1083]
**Environment**
- Ubuntu 24.04
- gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

**Reproduce**
- follow the install instructions for [pymesh](https://github.com/PyMesh/PyMesh) in a python 3.11 pyenv-virtualenv environment

**Error**
```
[ 66%] Building CXX object CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o
PyMesh/third_party/draco/src/draco/io/parser_utils.cc: In function ‘bool draco::parser::ParseFloat(draco::DecoderBuffer*, float*)’:
PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:16: error: ‘numeric_limits’ is not a member of ‘std’
  113 |       v = std::numeric_limits<double>::infinity();
      |                ^~~~~~~~~~~~~~
PyMesh/third_party/draco/src/draco/io/parser_utils.cc:113:31: error: expected primary-expression before ‘double’
  113 |       v = std::numeric_limits<double>::infinity();
      |                               ^~~~~~
gmake[2]: *** [CMakeFiles/draco_io.dir/build.make:118: CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:589: CMakeFiles/draco_io.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "PyMesh/third_party/build.py", line 82, in <module>
    main();
    ^^^^^^
  File "PyMesh/third_party/build.py", line 79, in main
    build(args.package, args.cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 59, in build
    build(libname, cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 75, in build
    build_generic(package, cleanup=cleanup);
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyMesh/third_party/build.py", line 47, in build_generic
    subprocess.check_call(cmd.split());
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip.sluzewski/.pyenv/versions/3.12.5/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', 'PyMesh/third_party/../third_party/build/draco']' returned non-zero exit status 2.
```

I am trying to build [pymesh](https://github.com/PyMesh/PyMesh), which uses draco as a dependency. During installation I encountered the error mentioned in #635 and manually corrected it, however I am now encountering the issue in #1076. The issue mentions updating to the latest release yet the git status for the dependency folder says that is up to date so I don't know what I should do to fix this problem.

**Comment by mfs4rd** [comment]
closing as the root issue is with pymesh using old forked dependencies that have not been updated
