### ISSUE TITLE
[Emscripten] IDL bindings glue generation fails on Windows

### ISSUE THREAD

**Issue by tomfinegan** [google/draco#190]
See my [comment](https://github.com/google/draco/issues/188#issuecomment-325006607) in #188 for a workaround.

At CMake generation time python will throw a couple of IOErrors when trying to run webidl_binder.py:

```
Traceback (most recent call last):
  File "D:\src\emsdk-portable\emscripten\1.37.20/tools/webidl_binder.py", line 752, in <module>
    c = open(output_base + '.cpp', 'w')
IOError: [Errno 13] Permission denied: 'D:/src/_werk/_builds/draco/emsdk/glue_decoder.cpp'
Traceback (most recent call last):
  File "D:\src\emsdk-portable\emscripten\1.37.20/tools/webidl_binder.py", line 752, in <module>
    c = open(output_base + '.cpp', 'w')
IOError: [Errno 13] Permission denied: 'D:/src/_werk/_builds/draco/emsdk/glue_encoder.cpp'
```

Not sure of the cause at present, but as noted in #188 this can be worked around by running the glue generation step manually.

**Comment by tomfinegan** [comment]
dc28e6a2eae53d48b22c668b6e8cad1c582a11ce fixes this.
