### ISSUE TITLE
Converting Draco Mesh to 3js and back

### ISSUE THREAD

**Issue by usmanshah** [google/draco#224]
I am experimenting with Draco using Angular4, Typescript and ThreeJs and trying to construct a dracoMesh using the data in a ThreeJs Geometry Object.

I add the face indices like so, where indices is a : 
`meshBuilder.AddFacesToMesh(dracoMesh, numFaces, indices);`
where `indices` is an array of indices of the points that form the faces

and then add the points (vertices) like this: 
`meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION, numPoints, 3, vertices);`

now after successfully executing these 2 lines, if i try to get these faces in a loop like this: 
```
for (let i = 0; i < numFaces; i++) {
    wrapper.GetFaceFromMesh(dracoMesh, i, ia);
}
```
I get an error like this: 
> core.es5.js:1020 ERROR Assertion failed: (face_id.value()) < (static_cast<int>(faces_.size())), at: ./mesh/mesh.h,64,face at Error
>     at jsStackTrace (http://localhost:4200/scripts.bundle.js:8822:17083)
>     at stackTrace (http://localhost:4200/scripts.bundle.js:8822:17254)
>     at ___assert_fail (http://localhost:4200/scripts.bundle.js:8822:81658)
>     at Di (http://localhost:4200/scripts.bundle.js:8829:81801)
>     at Qk (http://localhost:4200/scripts.bundle.js:8829:100482)
>     at WebIDLWrapper.DracoModule.WebIDLWrapper.GetFaceFromMesh.WebIDLWrapper.GetFaceFromMesh (http://localhost:4200/scripts.bundle.js:8836:18287)
>     at http://localhost:4200/main.bundle.js:4876:25
>     at Object.dracoDecoderType.onModuleLoaded (http://localhost:4200/scripts.bundle.js:8809:15)
>     at Object.DracoModule.Module.onModuleParsed (http://localhost:4200/scripts.bundle.js:8822:386)
>     at DracoModule (http://localhost:4200/scripts.bundle.js:8836:26062)

Also if i try to get the attributes i am setting, like so: 
```
let normalAttId = decoder.GetAttributeId(dracoMesh, decoderModule.NORMAL);
let positionAttId = decoder.GetAttributeId(dracoMesh, decoderModule.POSITION);
```

the values of `normalAttId` and `positionAttId` turn out to be **-1**;
which, as I understand, means that the attribute was not found on the dracoMesh.

This all suggests that i am not creating a `dracoMesh` object correctly in the first place, or I'm trying to retrieve the data incorrectly. 

**USE CASE DESCRIPTION** I have large(roughly 70-500 mb) 3js Geometry Objects (Initially loaded from Obj files), which I want to compress using Draco, store in the cloud and then load on demand.

Here is the complete typescript function (Not clean at all, as i'm experimenting). It just tries to convert a 3js Geometry Object to a DracoMesh and back. 

```
encodeMeshToDraco(mesh: THREE.Geometry): void {

        const encoderModule = createEncoderModule({});
        const decoderModule = createDecoderModule({});

        const encoder = new encoderModule.Encoder();
        const decoder = new decoderModule.Decoder();

        const meshBuilder = new encoderModule.MeshBuilder();
        const dracoMesh = new encoderModule.Mesh();

        const numFaces = mesh.faces.length;
        const numPoints = mesh.vertices.length;
        const numIndices = numFaces * 3;
        let indices = new Uint32Array(numIndices);

        console.log("Number of faces " + numFaces);
        console.log("Number of vertices " + numPoints);

        let vertices = new Float32Array(mesh.vertices.length * 3);
        let normals = new Float32Array(mesh.vertices.length * 3);

        // Add Faces to mesh
        for (let i = 0; i < numFaces; i++) {
            const index = i * 3;
            indices[index] = mesh.faces[i].a;
            indices[index + 1] = mesh.faces[i].b;
            indices[index + 2] = mesh.faces[i].c;
        }
        meshBuilder.AddFacesToMesh(dracoMesh, numFaces, indices);
        console.log(dracoMesh.num_faces());

        // Add POSITION to mesh (Vertices)
        for (let i = 0; i < mesh.vertices.length; i++) {
            const index = i * 3;
            vertices[index] = mesh.vertices[i].x;
            vertices[index + 1] = mesh.vertices[i].y;
            vertices[index + 2] = mesh.vertices[i].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION, numPoints, 3, vertices);

        // Add NORMAL to mesh
        for (let face of mesh.faces) {
            normals[face["a"] * 3] = face.vertexNormals[0].x;
            normals[(face["a"] * 3) + 1] = face.vertexNormals[0].y;
            normals[(face["a"] * 3) + 2] = face.vertexNormals[0].z;

            normals[face["b"] * 3] = face.vertexNormals[1].x;
            normals[(face["b"] * 3) + 1] = face.vertexNormals[1].y;
            normals[(face["b"] * 3) + 2] = face.vertexNormals[1].z;

            normals[face["c"] * 3] = face.vertexNormals[2].x;
            normals[(face["c"] * 3) + 1] = face.vertexNormals[2].y;
            normals[(face["c"] * 3) + 2] = face.vertexNormals[2].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.NORMAL, numPoints, 3, normals);

        // these stats show correct
        console.log("//DRACO MESH STATS//////////////////////////");
        console.log(dracoMesh);
        console.log(dracoMesh.num_faces());
        console.log(dracoMesh.num_points());
        console.log(dracoMesh.num_attributes());

        let normalAttId = decoder.GetAttributeId(dracoMesh, decoderModule.NORMAL);
        let positionAttId = decoder.GetAttributeId(dracoMesh, decoderModule.NORMAL);

        THREE.DRACOLoader.getDecoder({},
            function (dracoDecoder) {

                let loader = new THREE.DRACOLoader();
                let wrapper = new dracoDecoder.WebIDLWrapper();

                const posAttributeData = new dracoDecoder.DracoFloat32Array();
                // using '0' and '1' to identify POSITION and NORMAL, respectively;
                // because normalAttId and positionAttId come out to be -1 :/
                wrapper.GetAttributeFloatForAllPoints(dracoMesh, 0, posAttributeData);

                const norAttributeData = new dracoDecoder.DracoFloat32Array();
                decoder.GetAttributeFloatForAllPoints(dracoMesh, 1, norAttributeData);

                const numVertexCoordinates = dracoMesh.num_points() * 3;
                const geometryBuffer = {
                    indices: new Uint32Array(numIndices),
                    vertices: new Float32Array(numVertexCoordinates),
                    normals: new Float32Array(numVertexCoordinates)
                };

                for (let i = 0; i < numVertexCoordinates; i += 3) {
                    geometryBuffer.vertices[i] = posAttributeData.GetValue(i);
                    geometryBuffer.vertices[i + 1] = posAttributeData.GetValue(i + 1);
                    geometryBuffer.vertices[i + 2] = posAttributeData.GetValue(i + 2);

                    // Add normal.
                    if (normalAttId != -1) {
                        geometryBuffer.normals[i] = norAttributeData.GetValue(i);
                        geometryBuffer.normals[i + 1] = norAttributeData.GetValue(i + 1);
                        geometryBuffer.normals[i + 2] = norAttributeData.GetValue(i + 2);
                    }
                }


            }
        );
    }
```

Any help would be greatly appreciated.

**Comment by fanzhanggoogle** [comment]
Hi, from the first look, you did:
~~~js
let positionAttId = decoder.GetAttributeId(dracoMesh, decoderModule.NORMAL);
~~~
where `decoderModule.NORMAL` should be `decoderModule.POSITION`.

**Comment by usmanshah** [comment]
Oh, that was a typo. I corrected it but still the same behavior. 
I suspect the problem is either in the way i'm using  `AddFloatAttributeToMesh` OR in the way i'm using the **decoder**.

**Comment by fanzhanggoogle** [comment]
I see. So the `meshBuilder` is used to gather data of a mesh and pass to encoder to encode the data. I'm a bit confused because you didn't compress it in the code at all. The basic step should be 1) use meshBuilder to build a mesh 2) use the encoder to encode the data to a buffer. 
Then, on the decoding side you need to 1) decode mesh from the buffer 2) and build a ThreeJS mesh to render.

**Comment by fanzhanggoogle** [comment]
For reference, you can take a look at the [NodeJS example](https://github.com/google/draco/blob/1c7e96cba17e1fcbba370b8ec36525aaa839f856/javascript/npm/draco3d/draco_nodejs_example.js#L125) which might have some information that you need. It basically decoding from a compressed file, and build a mesh, and encode the mesh to another file.

**Comment by usmanshah** [comment]
The reason I am trying out this "reduced version" of the code is that I was not able to get the geometry data back from the decoded object, which led me to believe that I was not using the mesh builder correctly.
I have been using code form the same example you mentioned and the [DRACOLoader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/draco/DRACOLoader.js) from ThreeJs

Anyhow, below is the complete function that tries to: 
- build a Draco mesh using the mesh builder 
- add FaceIndices, normals and position arrays to the mesh
- Encode it
- Decode it
- Get the data arrays back and put them into a 3js object.

```
encodeMeshToDracoAndBack(mesh: THREE.Geometry): void {

        const encoderModule = createEncoderModule({});
        const decoderModule = createDecoderModule({});

        const encoder = new encoderModule.Encoder();
        const decoder = new decoderModule.Decoder();

        const meshBuilder = new encoderModule.MeshBuilder();
        const dracoMesh = new encoderModule.Mesh();

        const numFaces = mesh.faces.length;
        const numPoints = mesh.vertices.length;
        const numIndices = numFaces * 3;
        let indices = new Uint32Array(numIndices);

        console.log("Number of faces " + numFaces);
        console.log("Number of vertices " + numPoints);

        let vertices = new Float32Array(mesh.vertices.length * 3);
        let normals = new Float32Array(mesh.vertices.length * 3);

        // Add Faces to mesh
        for (let i = 0; i < numFaces; i++) {
            const index = i * 3;
            indices[index] = mesh.faces[i].a;
            indices[index + 1] = mesh.faces[i].b;
            indices[index + 2] = mesh.faces[i].c;
        }
        meshBuilder.AddFacesToMesh(dracoMesh, numFaces, indices);

        // Add POSITION to mesh (Vertices)
        for (let i = 0; i < mesh.vertices.length; i++) {
            const index = i * 3;
            vertices[index] = mesh.vertices[i].x;
            vertices[index + 1] = mesh.vertices[i].y;
            vertices[index + 2] = mesh.vertices[i].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION, numPoints, 3, vertices);

        // Add NORMAL to mesh
        for (let face of mesh.faces) {
            normals[face["a"] * 3] = face.vertexNormals[0].x;
            normals[(face["a"] * 3) + 1] = face.vertexNormals[0].y;
            normals[(face["a"] * 3) + 2] = face.vertexNormals[0].z;

            normals[face["b"] * 3] = face.vertexNormals[1].x;
            normals[(face["b"] * 3) + 1] = face.vertexNormals[1].y;
            normals[(face["b"] * 3) + 2] = face.vertexNormals[1].z;

            normals[face["c"] * 3] = face.vertexNormals[2].x;
            normals[(face["c"] * 3) + 1] = face.vertexNormals[2].y;
            normals[(face["c"] * 3) + 2] = face.vertexNormals[2].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.NORMAL, numPoints, 3, normals);

        console.log("//DRACO UNCOMPRESSED MESH STATS//////////");
        console.log("Number of faces " + dracoMesh.num_faces());
        console.log("Number of Vertices " + dracoMesh.num_points());
        console.log("Number of Attributes " + dracoMesh.num_attributes());


        // Compressing using DRACO
        let encodedData = new encoderModule.DracoInt8Array();
        encoder.SetSpeedOptions(5, 5);
        encoder.SetAttributeQuantization(encoderModule.POSITION, 10);
        encoder.SetEncodingMethod(encoderModule.MESH_EDGEBREAKER_ENCODING);

        console.log("Encoding...");
        const encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh, encodedData);
        encoderModule.destroy(dracoMesh);

        if (encodedLen > 0) {
            console.log("Encoded size is " + encodedLen);
        } else {
            console.log("Error: Encoding failed.");
        }

        // Copy encoded data to buffer.
        const outputBuffer = new ArrayBuffer(encodedLen);
        const outputData = new Int8Array(outputBuffer);
        for (let i = 0; i < encodedLen; ++i) {
            outputData[i] = encodedData.GetValue(i);
        }
        encoderModule.destroy(encodedData);
        encoderModule.destroy(encoder);
        encoderModule.destroy(meshBuilder);

        console.log("DRACO ENCODED////////////////////////////");
        console.log(outputData);

        //DECODING the DRACO ENCODED data as draco geometry object
        let inputToDecoder = new Buffer(outputBuffer);
        const buffer = new decoderModule.DecoderBuffer();
        buffer.Init(inputToDecoder, inputToDecoder.length);

        const geometryType = decoder.GetEncodedGeometryType(buffer);

        let uncompressedDracoMesh;
        if (geometryType == decoder.TRIANGULAR_MESH) {
            uncompressedDracoMesh = decoder.DecodeBufferToMesh(buffer);
        } else {
            uncompressedDracoMesh = decoder.DecodeBufferToPointCloud(buffer);
        }

        console.log("////draco geometry////////////////////////");
        console.log(uncompressedDracoMesh);

        decoderModule.destroy(buffer);

        THREE.DRACOLoader.getDecoder({},
            function (dracoDecoder) {

                let loader = new THREE.DRACOLoader();
                let wrapper = new dracoDecoder.WebIDLWrapper();

                let positionAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.POSITION);
                const posAttribute = decoder.GetAttribute(uncompressedDracoMesh, positionAttId);
                const posAttributeData = new dracoDecoder.DracoFloat32Array();
                decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, posAttribute, posAttributeData);

                let normalAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.NORMAL);
                let norAttributeData;
                if (normalAttId != -1) {
                    const norAttribute = decoder.GetAttribute(uncompressedDracoMesh, normalAttId);
                    norAttributeData = new dracoDecoder.DracoFloat32Array();
                    decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, norAttribute, norAttributeData);
                }

                // Converting to 3Js
                const numVertexCoordinates = uncompressedDracoMesh.num_points() * 3;
                const geometryBuffer = {
                    indices: new Uint32Array(numIndices),
                    vertices: new Float32Array(numVertexCoordinates),
                    normals: new Float32Array(numVertexCoordinates)
                };

                for (let i = 0; i < numVertexCoordinates; i += 3) {
                    geometryBuffer.vertices[i] = posAttributeData.GetValue(i);
                    geometryBuffer.vertices[i + 1] = posAttributeData.GetValue(i + 1);
                    geometryBuffer.vertices[i + 2] = posAttributeData.GetValue(i + 2);

                    // Add normal.
                    if (normalAttId != -1) {
                        geometryBuffer.normals[i] = norAttributeData.GetValue(i);
                        geometryBuffer.normals[i + 1] = norAttributeData.GetValue(i + 1);
                        geometryBuffer.normals[i + 2] = norAttributeData.GetValue(i + 2);
                    }
                }

                console.log("3Js Object");
                console.log(geometryBuffer);


            }
        );


    }
```

It fails while decoding when executing this line : `const norAttribute = decoder.GetAttribute(uncompressedDracoMesh, normalAttId);`

**OUTPUT**

> Number of faces 4968
> editor.component.ts:388 Number of vertices 14904
> editor.component.ts:427 //DRACO UNCOMPRESSED MESH STATS//////////
> editor.component.ts:428 Number of faces 4968
> editor.component.ts:429 Number of Vertices 14904
> editor.component.ts:430 Number of Attributes 2
> editor.component.ts:439 Encoding...
> editor.component.ts:444 Encoded size is 185895
> editor.component.ts:459 DRACO ENCODED////////////////////////////
> editor.component.ts:460 Int8Array(185895) [68, 82, 65, 67, 79, 2, 1, 1, 1, 0, 0, 0, 0, -57, 19, -24, 38, 1, -25, 38, -25, 1, -2, 9, -31, 4, 0, 0, 0, 0, 0, 0, 127, -101, -25, 75, -75, 84, -107, 86, -43, -6, 40, -86, -98, 122, 84, -75, -91, 90, 109, 91, 84, -75, 60, 74, -21, -117, 71, -107, 82, -113, 42, 45, 109, -87, -86, 22, 109, 91, -43, 82, 90, 90, 74, -97, 82, 85, -10, -108, 106, 105, -75, -76, 40, -21, 3, -113, -94, -49, 67, 85, 105, -85, 104, -87, -6, -38, 86, 117, …]
> editor.component.ts:476 ////draco geometry////////////////////////
> editor.component.ts:477 Status {ptr: 5271120}
> core.es5.js:1020 ERROR Assertion failed: (att_id) < (static_cast<int32_t>(attributes_.size())), at: /google/src/cloud/ostava/fix2/google3/third_party/draco/src/draco/point_cloud/point_cloud.h,59,attribute at Error
>     at jsStackTrace (http://localhost:4200/vendor.bundle.js:3117:17674)
>     at stackTrace (http://localhost:4200/vendor.bundle.js:3117:17845)
>     at ___assert_fail (http://localhost:4200/vendor.bundle.js:3117:110458)
>     at vn (http://localhost:4200/vendor.bundle.js:3125:31562)
>     at Up (http://localhost:4200/vendor.bundle.js:3125:42951)
>     at Decoder.CreateDracoModule.Decoder.GetAttribute.Decoder.GetAttribute (http://localhost:4200/vendor.bundle.js:3132:39981)
>     at http://localhost:4200/main.bundle.js:4887:40
>     at Object.dracoDecoderType.onModuleLoaded (http://localhost:4200/scripts.bundle.js:8809:15)
>     at Object.DracoModule.Module.onModuleParsed (http://localhost:4200/scripts.bundle.js:8822:386)
>     at DracoModule (http://localhost:4200/scripts.bundle.js:8836:26062)


Is there any obvious mistake i'm making ? Almost all of the code above is from the examples provided with draco and the [3js Draco Loader](https://github.com/mrdoob/three.js/tree/dev/examples/js/loaders/draco)

**Comment by fanzhanggoogle** [comment]
Hi, what version are you using? It's weird to me that in the code below
~~~js
        if (geometryType == decoder.TRIANGULAR_MESH) {
            uncompressedDracoMesh = decoder.DecodeBufferToMesh(buffer);
        } else {
            uncompressedDracoMesh = decoder.DecodeBufferToPointCloud(buffer);
        }
~~~
Our current API should be 
~~~js
        var dracoGeometry;
        var decodingStatus;
        if (geometryType === dracoDecoder.TRIANGULAR_MESH) {
          dracoGeometry = new dracoDecoder.Mesh();
          decodingStatus = decoder.DecodeBufferToMesh(buffer, dracoGeometry);
        } else {
          dracoGeometry = new dracoDecoder.PointCloud();
          decodingStatus =
              decoder.DecodeBufferToPointCloud(buffer, dracoGeometry);
        }
~~~
I believe it's the updated version in the DRACOLoader. Could you try this API?
Let me know if it works.

**Comment by usmanshah** [comment]
**[SOLVED]**
@fanzhanggoogle I tried the changes you suggested. They were a step in the right direction but the error was not gone. Then your comment about the "updated version" go my eye. 
I was initially using DRACOLoader for the ThreeJs repo, but that does not work interchangeably with the latest DRACOLoader in this repo. Now i switched to the DRACOLoader in this repo, and everything seems to work. 

So, below is the very-rough but working code, it constructs a **dracoMesh** from **Three Geometry**, **compresses** it, then **uncompresses** & constructs a three **BufferGeometry**: 

```
encodeMeshToDracoAndBack(mesh: THREE.Geometry): Mesh {

        const encoderModule = createEncoderModule({});
        const encoder = new encoderModule.Encoder();

        const meshBuilder = new encoderModule.MeshBuilder();
        const dracoMesh = new encoderModule.Mesh();

        const numFaces = mesh.faces.length;
        const numPoints = mesh.vertices.length;
        const numIndices = numFaces * 3;
        let indices = new Uint32Array(numIndices);

        console.log("Number of faces " + numFaces);
        console.log("Number of vertices " + numPoints);

        let vertices = new Float32Array(mesh.vertices.length * 3);
        let normals = new Float32Array(mesh.vertices.length * 3);

        // Add Faces to mesh
        for (let i = 0; i < numFaces; i++) {
            const index = i * 3;
            indices[index] = mesh.faces[i].a;
            indices[index + 1] = mesh.faces[i].b;
            indices[index + 2] = mesh.faces[i].c;
        }
        meshBuilder.AddFacesToMesh(dracoMesh, numFaces, indices);

        // Add POSITION to mesh (Vertices)
        for (let i = 0; i < mesh.vertices.length; i++) {
            const index = i * 3;
            vertices[index] = mesh.vertices[i].x;
            vertices[index + 1] = mesh.vertices[i].y;
            vertices[index + 2] = mesh.vertices[i].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.POSITION, numPoints, 3, vertices);

        // Add NORMAL to mesh
        for (let face of mesh.faces) {
            normals[face["a"] * 3] = face.vertexNormals[0].x;
            normals[(face["a"] * 3) + 1] = face.vertexNormals[0].y;
            normals[(face["a"] * 3) + 2] = face.vertexNormals[0].z;

            normals[face["b"] * 3] = face.vertexNormals[1].x;
            normals[(face["b"] * 3) + 1] = face.vertexNormals[1].y;
            normals[(face["b"] * 3) + 2] = face.vertexNormals[1].z;

            normals[face["c"] * 3] = face.vertexNormals[2].x;
            normals[(face["c"] * 3) + 1] = face.vertexNormals[2].y;
            normals[(face["c"] * 3) + 2] = face.vertexNormals[2].z;
        }
        meshBuilder.AddFloatAttributeToMesh(dracoMesh, encoderModule.NORMAL, numPoints, 3, normals);

        console.log("//DRACO UNCOMPRESSED MESH STATS//////////");
        console.log("Number of faces " + dracoMesh.num_faces());
        console.log("Number of Vertices " + dracoMesh.num_points());
        console.log("Number of Attributes " + dracoMesh.num_attributes());


        // Compressing using DRACO
        let encodedData = new encoderModule.DracoInt8Array();
        encoder.SetSpeedOptions(5, 5);
        encoder.SetAttributeQuantization(encoderModule.POSITION, 10);
        encoder.SetEncodingMethod(encoderModule.MESH_EDGEBREAKER_ENCODING);

        console.log("Encoding...");
        const encodedLen = encoder.EncodeMeshToDracoBuffer(dracoMesh, encodedData);
        encoderModule.destroy(dracoMesh);

        if (encodedLen > 0) {
            console.log("Encoded size is " + encodedLen);
        } else {
            console.log("Error: Encoding failed.");
        }

        // Copy encoded data to buffer.
        const outputBuffer = new ArrayBuffer(encodedLen);
        const outputData = new Int8Array(outputBuffer);
        for (let i = 0; i < encodedLen; ++i) {
            outputData[i] = encodedData.GetValue(i);
        }
        encoderModule.destroy(encodedData);
        encoderModule.destroy(encoder);
        encoderModule.destroy(meshBuilder);

        console.log("DRACO ENCODED////////////////////////////");
        console.log(outputData);


        //DECODING the DRACO ENCODED data as draco geometry object

        const decoderModule = createDecoderModule({});
        // const decoderModule = DracoDecoderModule();
        const decoder = new decoderModule.Decoder();


        let inputToDecoder = new Buffer(outputBuffer);
        const buffer = new decoderModule.DecoderBuffer();
        buffer.Init(inputToDecoder, inputToDecoder.length);
        const geometryType = decoder.GetEncodedGeometryType(buffer);

        let uncompressedDracoMesh;
        let decodingStatus;
        if (geometryType === decoderModule.TRIANGULAR_MESH) {
            uncompressedDracoMesh = new decoderModule.Mesh();
            decodingStatus = decoder.DecodeBufferToMesh(buffer, uncompressedDracoMesh);
        } else {
            uncompressedDracoMesh = new decoderModule.PointCloud();
            decodingStatus = decoder.DecodeBufferToPointCloud(buffer, uncompressedDracoMesh);
        }

        if (!decodingStatus.ok() || uncompressedDracoMesh.ptr == 0) {
            let errorMsg = "THREE.DRACOLoader: Decoding failed: ";
            errorMsg += decodingStatus.error_msg();
            console.error(errorMsg);
            decoderModule.destroy(decoder);
            decoderModule.destroy(uncompressedDracoMesh);
            throw new Error(errorMsg);
        }

        console.log("////draco geometry////////////////////////");
        console.log(uncompressedDracoMesh);
        decoderModule.destroy(buffer);


        let uncompressedNumFaces, uncompressedNumPoints;
        let numVertexCoordinates, numTextureCoordinates, numColorCoordinates;
        let numAttributes;
        let numColorCoordinateComponents = 3;

        // For output basic geometry information.
        if (geometryType == decoderModule.TRIANGULAR_MESH) {
            uncompressedNumFaces = uncompressedDracoMesh.num_faces();
            if (this.verbosity > 0) {
                console.log("Number of faces loaded: " + uncompressedNumFaces.toString());
            }
        } else {
            uncompressedNumFaces = 0;
        }
        uncompressedNumPoints = uncompressedDracoMesh.num_points();
        numVertexCoordinates = uncompressedNumPoints * 3;
        numTextureCoordinates = uncompressedNumPoints * 2;
        numColorCoordinates = uncompressedNumPoints * 3;
        numAttributes = uncompressedDracoMesh.num_attributes();
        if (this.verbosity > 0) {
            console.log("Number of points loaded: " + uncompressedNumPoints.toString());
            console.log("Number of attributes loaded: " +
                numAttributes.toString());
        }

        // Get position attribute. Must exists.
        let posAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.POSITION);
        if (posAttId == -1) {
            let errorMsg = "THREE.DRACOLoader: No position attribute found.";
            console.error(errorMsg);
            decoderModule.destroy(decoder);
            decoderModule.destroy(uncompressedDracoMesh);
            throw new Error(errorMsg);
        }
        let posAttribute = decoder.GetAttribute(uncompressedDracoMesh, posAttId);
        let posAttributeData = new decoderModule.DracoFloat32Array();
        decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, posAttribute, posAttributeData);

        // Get color attributes if exists.
        let colorAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.COLOR);
        let colAttributeData;
        if (colorAttId != -1) {
            if (this.verbosity > 0) {
                console.log("Loaded color attribute.");
            }
            let colAttribute = decoder.GetAttribute(uncompressedDracoMesh, colorAttId);
            if (colAttribute.num_components() === 4) {
                numColorCoordinates = uncompressedNumPoints * 4;
                numColorCoordinateComponents = 4;
            }
            colAttributeData = new decoderModule.DracoFloat32Array();
            decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, colAttribute, colAttributeData);
        }


        // Get normal attributes if exists.
        let normalAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.NORMAL);
        let norAttributeData;
        if (normalAttId != -1) {
            if (this.verbosity > 0) {
                console.log("Loaded normal attribute.");
            }
            let norAttribute = decoder.GetAttribute(uncompressedDracoMesh, normalAttId);
            norAttributeData = new decoderModule.DracoFloat32Array();
            decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, norAttribute, norAttributeData);
        }


        // Get texture coord attributes if exists.
        let texCoordAttId = decoder.GetAttributeId(uncompressedDracoMesh, decoderModule.TEX_COORD);
        let textCoordAttributeData;
        if (texCoordAttId != -1) {
            if (this.verbosity > 0) {
                console.log("Loaded texture coordinate attribute.");
            }
            let texCoordAttribute = decoder.GetAttribute(uncompressedDracoMesh, texCoordAttId);
            textCoordAttributeData = new decoderModule.DracoFloat32Array();
            decoder.GetAttributeFloatForAllPoints(uncompressedDracoMesh, texCoordAttribute, textCoordAttributeData);
        }

        // Structure for converting to THREEJS geometry later.
        let geometryBuffer = {
            vertices: new Float32Array(numVertexCoordinates),
            normals: new Float32Array(numVertexCoordinates),
            uvs: new Float32Array(numTextureCoordinates),
            colors: new Float32Array(numColorCoordinates),
            indices: null
        };

        for (let i = 0; i < numVertexCoordinates; i += 3) {
            geometryBuffer.vertices[i] = posAttributeData.GetValue(i);
            geometryBuffer.vertices[i + 1] = posAttributeData.GetValue(i + 1);
            geometryBuffer.vertices[i + 2] = posAttributeData.GetValue(i + 2);
            // Add normal.
            if (normalAttId != -1) {
                geometryBuffer.normals[i] = norAttributeData.GetValue(i);
                geometryBuffer.normals[i + 1] = norAttributeData.GetValue(i + 1);
                geometryBuffer.normals[i + 2] = norAttributeData.GetValue(i + 2);
            }
        }

        // Add color.
        for (let i = 0; i < numColorCoordinates; i += 1) {
            if (colorAttId != -1) {
                // Draco colors are already normalized.
                geometryBuffer.colors[i] = colAttributeData.GetValue(i);
            } else {
                // Default is white. This is faster than TypedArray.fill().
                geometryBuffer.colors[i] = 1.0;
            }
        }

        // Add texture coordinates.
        if (texCoordAttId != -1) {
            for (let i = 0; i < numTextureCoordinates; i += 2) {
                geometryBuffer.uvs[i] = textCoordAttributeData.GetValue(i);
                geometryBuffer.uvs[i + 1] = textCoordAttributeData.GetValue(i + 1);
            }
        }

        decoderModule.destroy(posAttributeData);
        if (colorAttId != -1)
            decoderModule.destroy(colAttributeData);
        if (normalAttId != -1)
            decoderModule.destroy(norAttributeData);
        if (texCoordAttId != -1)
            decoderModule.destroy(textCoordAttributeData);

        // For mesh, we need to generate the faces.
        if (geometryType == decoderModule.TRIANGULAR_MESH) {
            if (this.drawMode === THREE.TriangleStripDrawMode) {
                let stripsArray = new decoderModule.DracoInt32Array();
                decoder.GetTriangleStripsFromMesh(uncompressedDracoMesh, stripsArray);
                geometryBuffer.indices = new Uint32Array(stripsArray.size());
                for (let i = 0; i < stripsArray.size(); ++i) {
                    geometryBuffer.indices[i] = stripsArray.GetValue(i);
                }
                decoderModule.destroy(stripsArray);

            } else {
                let uncompressedNumIndices = uncompressedNumFaces * 3;
                geometryBuffer.indices = new Uint32Array(uncompressedNumIndices);
                let ia = new decoderModule.DracoInt32Array();
                for (let i = 0; i < uncompressedNumFaces; ++i) {
                    decoder.GetFaceFromMesh(uncompressedDracoMesh, i, ia);
                    let index = i * 3;
                    geometryBuffer.indices[index] = ia.GetValue(0);
                    geometryBuffer.indices[index + 1] = ia.GetValue(1);
                    geometryBuffer.indices[index + 2] = ia.GetValue(2);
                }
                decoderModule.destroy(ia);
            }
        }

        // Import data to Three JS geometry.
        let geometry = new THREE.BufferGeometry();
        geometry.drawMode = this.drawMode;
        if (geometryType == decoderModule.TRIANGULAR_MESH) {
            geometry.setIndex(new (geometryBuffer.indices.length > 65535 ? THREE.Uint32BufferAttribute : THREE.Uint16BufferAttribute)(geometryBuffer.indices, 1));
        }

        geometry.addAttribute("position", new THREE.Float32BufferAttribute(geometryBuffer.vertices, 3));
        let posTransform = new decoderModule.AttributeQuantizationTransform();

        if (posTransform.InitFromAttribute(posAttribute)) {

            // Quantized attribute. Store the quantization parameters into the
            // THREE.js attribute.
            geometry.attributes["position"].isQuantized = true;
            geometry.attributes["position"].maxRange = posTransform.range();
            geometry.attributes["position"].numQuantizationBits = posTransform.quantization_bits();
            geometry.attributes["position"].minValues = new Float32Array(3);
            for (let i = 0; i < 3; ++i) {
                geometry.attributes["position"].minValues[i] = posTransform.min_value(i);
            }
        }

        decoderModule.destroy(posTransform);
        geometry.addAttribute("color", new THREE.Float32BufferAttribute(geometryBuffer.colors, numColorCoordinateComponents));
        if (normalAttId != -1) {
            geometry.addAttribute("normal", new THREE.Float32BufferAttribute(geometryBuffer.normals, 3));
        }
        if (texCoordAttId != -1) {
            geometry.addAttribute("uv", new THREE.Float32BufferAttribute(geometryBuffer.uvs, 2));
        }

        decoderModule.destroy(decoder);
        decoderModule.destroy(uncompressedDracoMesh);

        // console.log(geometry);
        // let material = new THREE.MeshBasicMaterial({color: 0xffff00});
        return new THREE.Mesh(geometry);
    }
```

@fanzhanggoogle thanks for the help mate :]
