### ISSUE TITLE
heap-buffer-overflow in src/draco/core/draco_index_type.h

### ISSUE THREAD

**Issue by geeknik** [google/draco#281]
Well this was originally reported to the VRP on 18 January 2017 (3-6824000015918) and I was told that it was fixed on 3 April 2017, but it isn't fixed as of commit `5b09a85` so I'm going to go ahead and publicly disclose it here.

Compiled with Clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test2](https://github.com/google/draco/files/1451334/test2.gz)
```
=================================================================
==9224==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d000001278 at pc 0x000000618071 bp 0x7ffeb264a310 sp 0x7ffeb264a308
WRITE of size 4 at 0x61d000001278 thread T0
    #0 0x618070 in draco::IndexType<int, draco::CornerIndex_tag_type_>::operator=(draco::IndexType<int, draco::CornerIndex_tag_type_> const&) /root/draco/src/draco/core/draco_index_type.h:149:12
    #1 0x618070 in draco::CornerTable::SetOppositeCorner(draco::IndexType<int, draco::CornerIndex_tag_type_>, draco::IndexType<int, draco::CornerIndex_tag_type_>) /root/draco/src/draco/mesh/corner_table.h:211
    #2 0x61085b in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::SetOppositeCorners(draco::IndexType<int, draco::CornerIndex_tag_type_>, draco::IndexType<int, draco::CornerIndex_tag_type_>) /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.h:127:20
    #3 0x601c3a in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeConnectivity(int) /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:696:7
    #4 0x5eea7f in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:352:38
    #5 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #6 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #7 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #8 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #9 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #10 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #11 0x7fb66cc283f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #12 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

0x61d000001278 is located 0 bytes to the right of 2040-byte region [0x61d000000a80,0x61d000001278)
allocated by thread T0 here:
    #0 0x5b4e92 in operator new(unsigned long) (/root/draco/build/draco_decoder+0x5b4e92)
    #1 0x68bf6e in __gnu_cxx::new_allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> >::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/ext/new_allocator.h:104:27
    #2 0x68bf6e in std::allocator_traits<std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::allocate(std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> >&, unsigned long) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/alloc_traits.h:436
    #3 0x68bf6e in std::_Vector_base<draco::IndexType<int, draco::CornerIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:170
    #4 0x7f10f3 in std::_Vector_base<draco::IndexType<int, draco::CornerIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:185:33
    #5 0x7f0c18 in std::_Vector_base<draco::IndexType<int, draco::CornerIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::_Vector_base(unsigned long, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > const&) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:136:9
    #6 0x7f0a12 in std::vector<draco::IndexType<int, draco::CornerIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::vector(unsigned long, draco::IndexType<int, draco::CornerIndex_tag_type_> const&, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > const&) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:293:9
    #7 0x7f0132 in std::vector<draco::IndexType<int, draco::CornerIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::CornerIndex_tag_type_> > >::_M_fill_assign(unsigned long, draco::IndexType<int, draco::CornerIndex_tag_type_> const&) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/vector.tcc:230:11
    #8 0x7e4feb in draco::CornerTable::Reset(int) /root/draco/src/draco/mesh/corner_table.cc:58:21
    #9 0x5ea59d in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:257:23
    #10 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #11 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #12 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #13 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #14 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #15 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #16 0x7fb66cc283f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/draco/src/draco/core/draco_index_type.h:149:12 in draco::IndexType<int, draco::CornerIndex_tag_type_>::operator=(draco::IndexType<int, draco::CornerIndex_tag_type_> const&)
```

**Comment by ondys** [comment]
fixed in 1.2.1
