### ISSUE TITLE
signed integer overflow in src/draco/compression/mesh/mesh_sequential_decoder.cc

### ISSUE THREAD

**Issue by geeknik** [google/draco#282]
Compiled with clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test002](https://github.com/google/draco/files/1451343/test002.gz)

```
/root/draco/src/draco/compression/mesh/mesh_sequential_decoder.cc:124:50: runtime error: signed integer overflow: 808464432 * 3 cannot be represented in type 'int'
    #0 0x6f5315 in draco::MeshSequentialDecoder::DecodeAndDecompressIndices(int) /root/draco/src/draco/compression/mesh/mesh_sequential_decoder.cc:124:50
    #1 0x6f1632 in draco::MeshSequentialDecoder::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_sequential_decoder.cc:53:10
    #2 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #3 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #4 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #5 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #6 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #7 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #8 0x7f59110e53f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #9 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/compression/mesh/mesh_sequential_decoder.cc:124:50 in
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

**Comment by ondys** [comment]
fixed in 1.2.1
