### ISSUE TITLE
signed integer overflow in src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc

### ISSUE THREAD

**Issue by geeknik** [google/draco#283]
Compiled with clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test011](https://github.com/google/draco/files/1451365/test011.gz)

```
./draco_decoder -i test011
/root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:754:41: runtime error: signed integer overflow: 1226868100 - -1586192445 cannot be represented in type 'int'
    #0 0x5f560d in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeHoleAndTopologySplitEvents(draco::DecoderBuffer*) /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:754:41
    #1 0x5ee17a in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:330:9
    #2 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #3 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #4 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #5 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #6 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #7 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #8 0x7f59a7c443f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #9 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:754:41 in
==22434==AddressSanitizer's allocator is terminating the process instead of returning 0
==22434==If you don't like this behavior set allocator_may_return_null=1
==22434==AddressSanitizer CHECK failed: /b/build/slave/linux_upload_clang/build/src/third_party/llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:218 "((0)) != (0)" (0x0, 0x0)
    #0 0x5903b6 in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/root/draco/build/draco_decoder+0x5903b6)
    #1 0x5a587f in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/root/draco/build/draco_decoder+0x5a587f)
    #2 0x594853 in __sanitizer::ReportAllocatorCannotReturnNull() (/root/draco/build/draco_decoder+0x594853)
    #3 0x5948b8 in __sanitizer::ReturnNullOrDieOnFailure::OnOOM() (/root/draco/build/draco_decoder+0x5948b8)
    #4 0x4e9d38 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) (/root/draco/build/draco_decoder+0x4e9d38)
    #5 0x4e8636 in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) (/root/draco/build/draco_decoder+0x4e8636)
    #6 0x5b4f5c in operator new(unsigned long) (/root/draco/build/draco_decoder+0x5b4f5c)
    #7 0x6e6c1e in __gnu_cxx::new_allocator<draco::TopologySplitEventData>::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/ext/new_allocator.h:104:27
    #8 0x6e6c1e in std::allocator_traits<std::allocator<draco::TopologySplitEventData> >::allocate(std::allocator<draco::TopologySplitEventData>&, unsigned long) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/alloc_traits.h:436
    #9 0x6e6c1e in std::_Vector_base<draco::TopologySplitEventData, std::allocator<draco::TopologySplitEventData> >::_M_allocate(unsigned long) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:170
    #10 0x6e5887 in void std::vector<draco::TopologySplitEventData, std::allocator<draco::TopologySplitEventData> >::_M_emplace_back_aux<draco::TopologySplitEventData const&>(draco::TopologySplitEventData const&) /usr/lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/vector.tcc:412:28
    #11 0x5f5517 in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeHoleAndTopologySplitEvents(draco::DecoderBuffer*) /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:756:30
    #12 0x5ee17a in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalDecoder>::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:330:9
    #13 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #14 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #15 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #16 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #17 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #18 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #19 0x7f59a7c443f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #20 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

Aborted
```

**Comment by ondys** [comment]
fixed in 1.2.1
