### ISSUE TITLE
null pointer dereference in src/draco/attributes/geometry_attribute.h

### ISSUE THREAD

**Issue by geeknik** [google/draco#285]
Compiled with Clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test056](https://github.com/google/draco/files/1451432/test056.gz)

```
/root/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h:75:14: runtime error: member call on null pointer of type 'draco::GeometryAttribute'
    #0 0x9f80d7 in draco::MeshPredictionSchemeTexCoordsDecoder<int, draco::PredictionSchemeWrapDecodingTransform<int, int>, draco::MeshPredictionSchemeData<draco::CornerTable> >::SetParentAttribute(draco::PointAttribute const*) /root/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h:75:14
    #1 0xad79ac in draco::SequentialAttributeDecoder::InitPredictionScheme(draco::PredictionSchemeInterface*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoder.cc:83:16
    #2 0x950c3a in draco::SequentialIntegerAttributeDecoder::DecodeValues(std::vector<draco::IndexType<int, draco::PointIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::PointIndex_tag_type_> > > const&, draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:55:10
    #3 0x944845 in draco::SequentialAttributeDecodersController::DecodePortableAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:66:35
    #4 0x8e0a5e in draco::AttributesDecoder::DecodeAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/attributes_decoder.h:55:10
    #5 0x70269a in draco::PointCloudDecoder::DecodeAllAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:145:19
    #6 0x701c4a in draco::PointCloudDecoder::DecodePointAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:135:8
    #7 0x6ff32a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:93:8
    #8 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #9 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #10 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #11 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #12 0x7fe8ab3ce3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #13 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h:75:14 in
/root/draco/src/draco/attributes/geometry_attribute.h:194:8: runtime error: member call on null pointer of type 'const draco::GeometryAttribute *'
    #0 0x9f80f3 in draco::MeshPredictionSchemeTexCoordsDecoder<int, draco::PredictionSchemeWrapDecodingTransform<int, int>, draco::MeshPredictionSchemeData<draco::CornerTable> >::SetParentAttribute(draco::PointAttribute const*) /root/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h
    #1 0xad79ac in draco::SequentialAttributeDecoder::InitPredictionScheme(draco::PredictionSchemeInterface*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoder.cc:83:16
    #2 0x950c3a in draco::SequentialIntegerAttributeDecoder::DecodeValues(std::vector<draco::IndexType<int, draco::PointIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::PointIndex_tag_type_> > > const&, draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:55:10
    #3 0x944845 in draco::SequentialAttributeDecodersController::DecodePortableAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:66:35
    #4 0x8e0a5e in draco::AttributesDecoder::DecodeAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/attributes_decoder.h:55:10
    #5 0x70269a in draco::PointCloudDecoder::DecodeAllAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:145:19
    #6 0x701c4a in draco::PointCloudDecoder::DecodePointAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:135:8
    #7 0x6ff32a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:93:8
    #8 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #9 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #10 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #11 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #12 0x7fe8ab3ce3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #13 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/attributes/geometry_attribute.h:194:8 in
AddressSanitizer:DEADLYSIGNAL
=================================================================
==19492==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x0000009f7ec3 bp 0x7ffe461c17c0 sp 0x7ffe461c1780 T0)
==19492==The signal is caused by a READ memory access.
==19492==Hint: address points to the zero page.
    #0 0x9f7ec2 in draco::GeometryAttribute::attribute_type() const /root/draco/src/draco/attributes/geometry_attribute.h:194:40
    #1 0x9f7ec2 in draco::MeshPredictionSchemeTexCoordsDecoder<int, draco::PredictionSchemeWrapDecodingTransform<int, int>, draco::MeshPredictionSchemeData<draco::CornerTable> >::SetParentAttribute(draco::PointAttribute const*) /root/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h:75
    #2 0xad79ac in draco::SequentialAttributeDecoder::InitPredictionScheme(draco::PredictionSchemeInterface*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoder.cc:83:16
    #3 0x950c3a in draco::SequentialIntegerAttributeDecoder::DecodeValues(std::vector<draco::IndexType<int, draco::PointIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::PointIndex_tag_type_> > > const&, draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:55:10
    #4 0x944845 in draco::SequentialAttributeDecodersController::DecodePortableAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:66:35
    #5 0x8e0a5e in draco::AttributesDecoder::DecodeAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/attributes_decoder.h:55:10
    #6 0x70269a in draco::PointCloudDecoder::DecodeAllAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:145:19
    #7 0x701c4a in draco::PointCloudDecoder::DecodePointAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:135:8
    #8 0x6ff32a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:93:8
    #9 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #10 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #11 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #12 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #13 0x7fe8ab3ce3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #14 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/draco/src/draco/attributes/geometry_attribute.h:194:40 in draco::GeometryAttribute::attribute_type() const
==19492==ABORTING
Aborted
```

**Comment by ondys** [comment]
fixed in 1.2.1
