### ISSUE TITLE
signed integer overflow in src/draco/compression/attributes/sequential_quantization_attribute_decoder.cc

### ISSUE THREAD

**Issue by geeknik** [google/draco#286]
Compiled with Clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test073](https://github.com/google/draco/files/1451448/test073.gz)

```
/root/draco/src/draco/compression/attributes/sequential_quantization_attribute_decoder.cc:85:67: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'
    #0 0xa97c27 in draco::SequentialQuantizationAttributeDecoder::DequantizeValues(unsigned int) /root/draco/src/draco/compression/attributes/sequential_quantization_attribute_decoder.cc:85:67
    #1 0x945e81 in draco::SequentialAttributeDecodersController::TransformAttributesToOriginalFormat() /root/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:104:35
    #2 0x70269a in draco::PointCloudDecoder::DecodeAllAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:145:19
    #3 0x701c4a in draco::PointCloudDecoder::DecodePointAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:135:8
    #4 0x6ff32a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:93:8
    #5 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #6 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #7 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #8 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #9 0x7f36944ec3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #10 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/compression/attributes/sequential_quantization_attribute_decoder.cc:85:67 in
Decoded geometry saved to test073.ply (72 ms to decode)
```

**Comment by ondys** [comment]
fixed in 1.2.1
