### ISSUE TITLE
signed integer overflow in src/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_decoding_transform.h

### ISSUE THREAD

**Issue by geeknik** [google/draco#288]
Compiled with Clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test084](https://github.com/google/draco/files/1451642/test084.gz)

```
/root/draco/src/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_decoding_transform.h:43:30: runtime error: signed integer overflow: 1073815566 - -1073741803 cannot be represented in type 'int'
    #0 0x965093 in draco::PredictionSchemeWrapDecodingTransform<int, int>::ComputeOriginalValue(int const*, int const*, int*) const /root/draco/src/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_decoding_transform.h:43:30
    #1 0xa0adb7 in draco::PredictionSchemeDeltaDecoder<int, draco::PredictionSchemeWrapDecodingTransform<int, int> >::ComputeOriginalValues(int const*, int*, int, int, draco::IndexType<int, draco::PointIndex_tag_type_> const*) /root/draco/src/draco/compression/attributes/prediction_schemes/prediction_scheme_delta_decoder.h:57:23
    #2 0x95302d in draco::SequentialIntegerAttributeDecoder::DecodeIntegerValues(std::vector<draco::IndexType<int, draco::PointIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::PointIndex_tag_type_> > > const&, draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:137:32
    #3 0x950e25 in draco::SequentialIntegerAttributeDecoder::DecodeValues(std::vector<draco::IndexType<int, draco::PointIndex_tag_type_>, std::allocator<draco::IndexType<int, draco::PointIndex_tag_type_> > > const&, draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:59:8
    #4 0x944845 in draco::SequentialAttributeDecodersController::DecodePortableAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:66:35
    #5 0x8e0a5e in draco::AttributesDecoder::DecodeAttributes(draco::DecoderBuffer*) /root/draco/src/draco/compression/attributes/attributes_decoder.h:55:10
    #6 0x70269a in draco::PointCloudDecoder::DecodeAllAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:145:19
    #7 0x701c4a in draco::PointCloudDecoder::DecodePointAttributes() /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:135:8
    #8 0x6ff32a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:93:8
    #9 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #10 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #11 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #12 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #13 0x7f6ce757e3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #14 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/draco/src/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_decoding_transform.h:43:30 in
Failed to decode the input file Failed to decode point attributes.
```

**Comment by ondys** [comment]
fixed in 1.2.1
