### ISSUE TITLE
null pointer dereference in /src/draco/compression/mesh/mesh_edgebreaker_traversal_valence_decoder.h

### ISSUE THREAD

**Issue by geeknik** [google/draco#289]
Compiled with Clang 6.0.0-trunk and -fsanitize=address,undefined.

./draco_decoder -i [test117](https://github.com/google/draco/files/1451663/test117.gz)

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==5771==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000677c70 bp 0x7ffefd8b75f0 sp 0x7ffefd8b75b0 T0)
==5771==The signal is caused by a READ memory access.
==5771==Hint: address points to the zero page.
    #0 0x677c6f in draco::MeshEdgeBreakerTraversalValenceDecoder::DecodeSymbol() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_traversal_valence_decoder.h:107:11
    #1 0x661a2a in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalValenceDecoder>::DecodeConnectivity(int) /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:454:48
    #2 0x65928a in draco::MeshEdgeBreakerDecoderImpl<draco::MeshEdgeBreakerTraversalValenceDecoder>::DecodeConnectivity() /root/draco/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:352:38
    #3 0x5d4a68 in draco::MeshDecoder::DecodeGeometryData() /root/draco/src/draco/compression/mesh/mesh_decoder.cc:30:8
    #4 0x6ff25a in draco::PointCloudDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::PointCloud*) /root/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:91:8
    #5 0x5d47db in draco::MeshDecoder::Decode(draco::DracoOptions<draco::GeometryAttribute::Type> const&, draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/mesh/mesh_decoder.cc:24:29
    #6 0x5c4c5c in draco::Decoder::DecodeBufferToGeometry(draco::DecoderBuffer*, draco::Mesh*) /root/draco/src/draco/compression/decode.cc:121:3
    #7 0x5c529e in draco::Decoder::DecodeMeshFromBuffer(draco::DecoderBuffer*) /root/draco/src/draco/compression/decode.cc:86:3
    #8 0x5b919f in main /root/draco/src/draco/tools/draco_decoder.cc:104:29
    #9 0x7f0ff77ea3f0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x203f0)
    #10 0x4e7cd9 in _start (/root/draco/build/draco_decoder+0x4e7cd9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/draco/src/draco/compression/mesh/mesh_edgebreaker_traversal_valence_decoder.h:107:11 in draco::MeshEdgeBreakerTraversalValenceDecoder::DecodeSymbol()
==5771==ABORTING
Aborted
```

**Comment by ondys** [comment]
fixed in 1.2.1
