### ISSUE TITLE
Javascript decoder raises error when qp value increased while encoding.

### ISSUE THREAD

**Issue by shubhamagarwal003** [google/draco#297]
Hi, 
Javscript decoder raises following error 
```
draco_decoder.js:5 Uncaught Assertion failed: (normal.AbsSum()) <= (upper_bound), at: /google/src/cloud/ostava/fix/google3/third_party/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h,95,ComputePredictedValue at Error
    at jsStackTrace (http://localhost:8000/draco_decoder.js:5:17619)
    at stackTrace (http://localhost:8000/draco_decoder.js:5:17790)
    at ___assert_fail (http://localhost:8000/draco_decoder.js:5:92938)
    at Rb (http://localhost:8000/draco_decoder.js:9:69952)
    at Array.ec (http://localhost:8000/draco_decoder.js:9:106312)
    at ic (http://localhost:8000/draco_decoder.js:9:116328)
    at Array.Mg (http://localhost:8000/draco_decoder.js:10:133362)
    at Array.fe (http://localhost:8000/draco_decoder.js:10:44075)
    at Array.ij (http://localhost:8000/draco_decoder.js:10:170593)
    at Array.Xh (http://localhost:8000/draco_decoder.js:10:155493)
```
when I tried to encode mesh with higher Position Quantization Parameter (-qp generally greater than 20). I tried for multiple meshes but the same error occurs for them. For smaller qp the encoded file is successfully decoded.

**Comment by fanzhanggoogle** [comment]
@shubhamagarwal003 Thanks for the report. Will you be able to send a sample model that fails decoding so that I could test to what's the problem?

**Comment by shubhamagarwal003** [comment]
@fanzhanggoogle I've uploaded one of the test model on google drive. Link to that is https://drive.google.com/drive/folders/13tMxLiFy1fIQFZ_EZIbFFEChOLvg0iHH?usp=sharing

**Comment by FrankGalligan** [comment]
This has been fixed for a while. Just tested up to -qp 30 and decoded fine.
