### ISSUE TITLE
SIGSEGV: in draco::rabs_desc_read 

### ISSUE THREAD

**Issue by najadojo** [google/draco#396]
Using american fuzzy lop 2.49b on draco_decoder I found a crash at the stack:

```
#0  0x00005555555c2193 in draco::rabs_desc_read (ans=0x7fffffffd3f0, p0=149 '\225')
    at /home/jamie/draco/src/draco/core/ans.h:176
#1  0x00005555555c2509 in draco::RAnsBitDecoder::DecodeNextBit (this=0x7fffffffd3f0)
    at /home/jamie/draco/src/draco/core/bit_coders/rans_bit_decoder.cc:58
#2  0x0000555555659898 in draco::MeshPredictionSchemeConstrainedMultiParallelogramDecoder<int, draco::PredictionSchemeWrapDecodingTransform<int, int>, draco::MeshPredictionSchemeData<draco::CornerTable> >::DecodePredictionData (
    this=0x55555593cdd0, buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_constrained_multi_parallelogram_decoder.h:212
#3  0x000055555565304c in draco::SequentialIntegerAttributeDecoder::DecodeIntegerValues (this=0x55555593b870, 
    point_ids=std::__debug::vector of length 8, capacity 8 = {...}, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:137
#4  0x000055555566b88c in draco::SequentialQuantizationAttributeDecoder::DecodeIntegerValues (this=0x55555593b870, 
    point_ids=std::__debug::vector of length 8, capacity 8 = {...}, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_quantization_attribute_decoder.cc:45
#5  0x0000555555652bf9 in draco::SequentialIntegerAttributeDecoder::DecodeValues (this=0x55555593b870, 
    point_ids=std::__debug::vector of length 8, capacity 8 = {...}, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:60
#6  0x00005555556791a7 in draco::SequentialAttributeDecoder::DecodePortableAttribute (this=0x55555593b870, 
    point_ids=std::__debug::vector of length 8, capacity 8 = {...}, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_attribute_decoder.cc:41
#7  0x000055555565029a in draco::SequentialAttributeDecodersController::DecodePortableAttributes (
    this=0x55555593c290, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:66
#8  0x000055555562d678 in draco::AttributesDecoder::DecodeAttributes (this=0x55555593c290, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/attributes_decoder.h:57
#9  0x0000555555650218 in draco::SequentialAttributeDecodersController::DecodeAttributes (this=0x55555593c290, 
    buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/attributes/sequential_attribute_decoders_controller.cc:59
#10 0x00005555555b18bf in draco::PointCloudDecoder::DecodeAllAttributes (this=0x55555593a7e0)
    at /home/jamie/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:151
#11 0x00005555555b178e in draco::PointCloudDecoder::DecodePointAttributes (this=0x55555593a7e0)
    at /home/jamie/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:141
#12 0x00005555555b1258 in draco::PointCloudDecoder::Decode (this=0x55555593a7e0, options=..., 
    in_buffer=0x7fffffffda70, out_point_cloud=0x55555593a600)
    at /home/jamie/draco/src/draco/compression/point_cloud/point_cloud_decoder.cc:99
#13 0x0000555555570fd1 in draco::MeshDecoder::Decode (this=0x55555593a7e0, options=..., in_buffer=0x7fffffffda70, 
    out_mesh=0x55555593a600) at /home/jamie/draco/src/draco/compression/mesh/mesh_decoder.cc:24
#14 0x000055555556c7e4 in draco::Decoder::DecodeBufferToGeometry (this=0x7fffffffdab0, in_buffer=0x7fffffffda70, 
    out_geometry=0x55555593a600) at /home/jamie/draco/src/draco/compression/decode.cc:121
#15 0x000055555556c169 in draco::Decoder::DecodeMeshFromBuffer (this=0x7fffffffdab0, in_buffer=0x7fffffffda70)
    at /home/jamie/draco/src/draco/compression/decode.cc:86
```

./draco_decoder -i [id:000233,sig:11,src:000605,op:arith8,pos:68,val:+3](https://github.com/google/draco/files/2027656/id.000233.sig.11.src.000605.op.arith8.pos.68.val.3.gz)

**Comment by najadojo** [comment]
Probably a duplicate of #397
