### ISSUE TITLE
NPM module draco3d draco_encoder fails with large meshes

### ISSUE THREAD

**Issue by JuliaWinchester** [google/draco#571]
I am trying to run the [draco_nodejs_example.js](https://github.com/google/draco/blob/master/javascript/npm/draco3d/draco_nodejs_example.js) script included with the draco3d NPM module. The script by default works fine, decoding and re-encoding the included bunny.drc file. But when I replace bunny.drc with a much larger mesh.drc (19378248 faces and 9684247 vertices), the script fails during the "Encoding..." step. This seems to be related to how the draco_encoder was compiled with Emscripten. I'm attaching a ZIP archive containing mesh.drc and a version of draco_nodejs_example.js that has been modified to load mesh.drc instead of bunny.drc. I'll also include the full command output from attempting to run the script. Thanks!

[draco3d_large_mesh_issue.zip](https://github.com/google/draco/files/4061295/draco3d_large_mesh_issue.zip)

```
user$ node draco_nodejs_example.js
Decoding file of size 16386079 ..
Number of faces 19378248
Number of vertices 9684247
Adding POSITION attribute
Encoding...
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 1895825408, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 1895825408, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

/Users/user/code/draco-test/node_modules/draco3d/draco_decoder_nodejs.js:5
var Module=typeof DracoDecoderModule!=="undefined"?DracoDecoderModule:{};var isRuntimeInitialized=false;var isModuleParsed=false;Module["onRuntimeInitialized"]=(function(){isRuntimeInitialized=true;if(isModuleParsed){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}});Module["onModuleParsed"]=(function(){isModuleParsed=true;if(isRuntimeInitialized){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}});function isVersionSupported(versionString){if(typeof versionString!=="string")return false;const version=versionString.split(".");if(version.length<2||version.length>3)return false;if(version[0]==1&&version[1]>=0&&version[1]<=3)return true;if(version[0]!=0||version[1]>10)return false;return true}Module["isVersionSupported"]=isVersionSupported;var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["argume
abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 1895825408, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.
```

**Comment by ryanfb** [comment]
It seems like the `draco_decoder_nodejs.js`/`draco_encoder_nodejs.js` files in `javascript/npm/draco3d` (and as a result, the distributed `npm3d` module as well) for some reason haven't been compiled with `-s ALLOW_MEMORY_GROWTH=1`, despite this being the default in `CMakeLists.txt`.

Based on my own testing trying to rebuild these scripts from scratch, it looks like somewhere between emscripten 1.38.31 and 1.39.8, the CMake feature detection for this flag started failing. I've been unable to re-create these scripts successfully so far (on the 1.3.5 tag) - with emscripten 1.38.31, I always got WASM output, even after passing `-DENABLE_WASM=OFF` to the `cmake` command before building with emscripten, and the resulting node module would fail the example script with the error:
```
TypeError: Cannot read property 'apply' of undefined
    at a._emscripten_bind_Decoder_Decoder_0 (/Users/ryan/mess/2020/08/draco/javascript/npm/draco3d/draco_decoder_nodejs.js:41:112)
    at new g (/Users/ryan/mess/2020/08/draco/javascript/npm/draco3d/draco_decoder_nodejs.js:22:43)
    at /Users/ryan/mess/2020/08/draco/javascript/npm/draco3d/draco_nodejs_example.js:29:19
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```
I upgraded emscripten to 1.39.8 to see if that resolved things, and noticed the above-described autoconfiguration failure, but then my build started failing due to issues with configuring binaryen under OS X Homebrew.

I'm going to try to get a reproducible build working in a Dockerized environment, experiment further with that, and report back.

**Comment by ryanfb** [comment]
Unfortunately, after further investigation, it seems like this might actually be an upstream issue with a 2GB memory ceiling in emscripten/node: https://github.com/emscripten-core/emscripten/issues/6566

I've tried the potential workaround suggested here while using a compiled-from-scratch version with `ALLOW_MEMORY_GROWTH=1` and still ran into the same problem: https://gist.github.com/motss/f55b92ccab0d434fa6e6cfd07423014b

Here's a `Dockerfile` that will let you test/reproduce the issue (you can uncomment the `ADD CMakeLists.txt` line to use a local `CMakeLists.txt` with additional definitions, like `-s ASSERTIONS=1`):
```
FROM trzeci/emscripten

RUN git clone https://github.com/google/draco.git
WORKDIR /src/draco
RUN git checkout 1.3.5
# ADD CMakeLists.txt /src/draco/CMakeLists.txt
RUN mkdir build
WORKDIR /src/draco/build
RUN cmake .. -DCMAKE_TOOLCHAIN_FILE=/emsdk_portable/emscripten/tag-1.38.45/cmake/Modules/Platform/Emscripten.cmake
RUN make
RUN cp -v *.wasm ../javascript/npm/draco3d/
RUN cp -v draco_decoder.js ../javascript/npm/draco3d/draco_decoder_nodejs.js
RUN cp -v draco_encoder.js ../javascript/npm/draco3d/draco_encoder_nodejs.js
WORKDIR /src/draco/javascript/npm/draco3d
RUN npm link
RUN npm link draco3d
RUN node draco_nodejs_example.js
RUN wget 'https://github.com/google/draco/files/4061295/draco3d_large_mesh_issue.zip'
RUN unzip -o draco3d_large_mesh_issue.zip
RUN node draco_nodejs_example.js
```

**Comment by JuliaWinchester** [comment]
As a bit of further context, for .drc-format Draco meshes it would be possible to use the command line Draco extension, but current tools to draco-compress GLTF meshes seem to largely rely on the Javascript encoder. So this forms a hard blocker for the ability to create draco-compressed GLTFs of large meshes using current tools.

**Comment by ryanfb** [comment]
As a note for testing limits with new upstream releases, you should be able to retry the Docker build above with a 4GB memory ceiling using an emscripten release of 1.39.12 or later, building with MAXIMUM_MEMORY set to 4294967296, using node v15 or later once it releases in order to run on V8 8.3 or later which has the WebAssembly memory increase merged.

**Comment by tomfinegan** [comment]
Is this still an issue? All of the javascript builds in v1.4.1 are configured with ALLOW_MEMORY_GROWTH=1, and beyond that based on my reading here it appears that the underlying problem is an Emscripten issue that is beyond the control of the Draco project.
