### ISSUE TITLE
Creating a encoderModule triggers a  `TypeError`

### ISSUE THREAD

**Issue by Samulus** [google/draco#583]
After upgrading from 1.3.4 to 1.3.6 creating an instance of a draco encoder triggers the following exception:

```
$ node lib/minimal.js 
C:\Code\3d-tiles-validator-c\samples-generator\node_modules\draco3d\draco_encoder_nodejs.js:9
var Module=typeof DracoEncoderModule!=="undefined"?DracoEncoderModule:{};var isRuntimeInitialized=false;var isModuleParsed=false;Module["onRuntimeInitialized"]=function(){isRuntimeInitialized=true;if(isModuleParsed){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}};Module["onModuleParsed"]=function(){isModuleParsed=true;if(isRuntimeInitialized){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}};function isVersionSupported(versionString){if(typeof versionString!=="string")return false;const version=versionString.split(".");if(version.length<2||version.length>3)return false;if(version[0]==1&&version[1]>=0&&version[1]<=3)return true;if(version[0]!=0||version[1]>10)return false;return true}Module["isVersionSupported"]=isVersionSupported;var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}v

TypeError: Cannot read property 'apply' of undefined
    at Module._emscripten_bind_Encoder_Encoder_0 (C:\Code\3d-tiles-validator-c\samples-generator\node_modules\draco3d\draco_encoder_nodejs.js:39:23094)
    at new Encoder (C:\Code\3d-tiles-validator-c\samples-generator\node_modules\draco3d\draco_encoder_nodejs.js:39:50343)
    at Object.<anonymous> (C:\Code\3d-tiles-validator-c\samples-generator\lib\minimal.js:3:15)
```

lib/minimal.js
```
var draco3d = require('draco3d');
var encoderModule = draco3d.createEncoderModule({});
var encoder = new encoderModule.Encoder();
```

**Comment by FrankGalligan** [comment]
I tired encoding with gltf-pipeline and draco3d 1.3.6 without any issues

**Comment by FrankGalligan** [comment]
So I think this is a timing issue that we have run into in the past. But we are seeing it more now when the code was built with a newer emscripten.

```
var draco3d = require('draco3d');
var encoder = null;
var dracoEncoderType = {};
dracoEncoderType['onModuleLoaded'] = function(module) {
  encoder = new module.Encoder();
};
var encoderModule = draco3d.createEncoderModule(dracoEncoderType);
```

Can you try this code? Also you will need to wait for the callback `onModuleLoaded` to be called before you can use `encoder`.

**Comment by FrankGalligan** [comment]
Also I could reproduce the issue using the minimal.js.

**Comment by Samulus** [comment]
Yeah that code solved the issue, can't reproduce the crash anymore thanks!

**Comment by FrankGalligan** [comment]
Closing due to inactivity. Please reopen if still an issue.
