### ISSUE TITLE
WASM error

### ISSUE THREAD

**Issue by LordAcrobaticTurtle** [google/draco#973]
Hi Everyone

Running a typescript application on a Nvidia Jetson device. 
I used npm install draco3d to install the library, and I am currently trying to decode the point cloud that is being sent over the network.
I have a line of code that calls the "createDecoderModule", however everytime I call it, it throws this error. 
I am fairly new to Typescript and have no experience in web assembly so I would really appreciate some advice if anyone can offer some. 

Thanks
```
react_devtools_backend.js:4012 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
overrideMethod @ react_devtools_backend.js:4012
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
(anonymous) @ draco_decoder_nodejs.js:40
(anonymous) @ draco_decoder_nodejs.js:40
DracoPointCloudWrapper @ draco_point_cloud_wrapper.tsx:25
RobotWorkspace @ robot_workspace.tsx:30
ThreeScene @ three_scene.tsx:49
initialiseRefs @ app.tsx:28
(anonymous) @ app.tsx:39
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ react_devtools_backend.js:6578
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:85
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:83
executeRuntime @ RefreshUtils.js:243
$ReactRefreshModuleRuntime$ @ app.tsx:10
./src/app.tsx @ app.tsx:10
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
_requireSelf @ hot module replacement:102
apply @ jsonp chunk loading:407
(anonymous) @ hot module replacement:344
internalApply @ hot module replacement:342
(anonymous) @ hot module replacement:279
waitForBlockingPromises @ hot module replacement:233
(anonymous) @ hot module replacement:277
Promise.then (async)
(anonymous) @ hot module replacement:276
Promise.then (async)
(anonymous) @ hot module replacement:256
Promise.then (async)
hotCheck @ hot module replacement:247
check @ dev-server.js:13
(anonymous) @ dev-server.js:68
emit @ events.js:153
reloadApp @ reloadApp.js:46
warnings @ index.js:261
(anonymous) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
react_devtools_backend.js:4012 falling back to ArrayBuffer instantiation
overrideMethod @ react_devtools_backend.js:4012
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
(anonymous) @ draco_decoder_nodejs.js:40
(anonymous) @ draco_decoder_nodejs.js:40
DracoPointCloudWrapper @ draco_point_cloud_wrapper.tsx:25
RobotWorkspace @ robot_workspace.tsx:30
ThreeScene @ three_scene.tsx:49
initialiseRefs @ app.tsx:28
(anonymous) @ app.tsx:39
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ react_devtools_backend.js:6578
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:85
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:83
executeRuntime @ RefreshUtils.js:243
$ReactRefreshModuleRuntime$ @ app.tsx:10
./src/app.tsx @ app.tsx:10
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
_requireSelf @ hot module replacement:102
apply @ jsonp chunk loading:407
(anonymous) @ hot module replacement:344
internalApply @ hot module replacement:342
(anonymous) @ hot module replacement:279
waitForBlockingPromises @ hot module replacement:233
(anonymous) @ hot module replacement:277
Promise.then (async)
(anonymous) @ hot module replacement:276
Promise.then (async)
(anonymous) @ hot module replacement:256
Promise.then (async)
hotCheck @ hot module replacement:247
check @ dev-server.js:13
(anonymous) @ dev-server.js:68
emit @ events.js:153
reloadApp @ reloadApp.js:46
warnings @ index.js:261
(anonymous) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
react_devtools_backend.js:4012 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
overrideMethod @ react_devtools_backend.js:4012
(anonymous) @ draco_decoder_nodejs.js:38
Promise.then (async)
c @ draco_decoder_nodejs.js:38
(anonymous) @ draco_decoder_nodejs.js:40
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
(anonymous) @ draco_decoder_nodejs.js:40
(anonymous) @ draco_decoder_nodejs.js:40
DracoPointCloudWrapper @ draco_point_cloud_wrapper.tsx:25
RobotWorkspace @ robot_workspace.tsx:30
ThreeScene @ three_scene.tsx:49
initialiseRefs @ app.tsx:28
(anonymous) @ app.tsx:39
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ react_devtools_backend.js:6578
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:85
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:83
executeRuntime @ RefreshUtils.js:243
$ReactRefreshModuleRuntime$ @ app.tsx:10
./src/app.tsx @ app.tsx:10
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
_requireSelf @ hot module replacement:102
apply @ jsonp chunk loading:407
(anonymous) @ hot module replacement:344
internalApply @ hot module replacement:342
(anonymous) @ hot module replacement:279
waitForBlockingPromises @ hot module replacement:233
(anonymous) @ hot module replacement:277
Promise.then (async)
(anonymous) @ hot module replacement:276
Promise.then (async)
(anonymous) @ hot module replacement:256
Promise.then (async)
hotCheck @ hot module replacement:247
check @ dev-server.js:13
(anonymous) @ dev-server.js:68
emit @ events.js:153
reloadApp @ reloadApp.js:46
warnings @ index.js:261
(anonymous) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
react_devtools_backend.js:4012 Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0)
overrideMethod @ react_devtools_backend.js:4012
f @ draco_decoder_nodejs.js:24
(anonymous) @ draco_decoder_nodejs.js:38
Promise.then (async)
c @ draco_decoder_nodejs.js:38
(anonymous) @ draco_decoder_nodejs.js:40
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
Promise.then (async)
(anonymous) @ draco_decoder_nodejs.js:39
(anonymous) @ draco_decoder_nodejs.js:40
(anonymous) @ draco_decoder_nodejs.js:40
DracoPointCloudWrapper @ draco_point_cloud_wrapper.tsx:25
RobotWorkspace @ robot_workspace.tsx:30
ThreeScene @ three_scene.tsx:49
initialiseRefs @ app.tsx:28
(anonymous) @ app.tsx:39
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
scheduleRefresh @ react-dom.development.js:27795
renderer.scheduleRefresh @ react_devtools_backend.js:6578
(anonymous) @ react-refresh-runtime.development.js:304
performReactRefresh @ react-refresh-runtime.development.js:293
(anonymous) @ RefreshUtils.js:85
setTimeout (async)
enqueueUpdate @ RefreshUtils.js:83
executeRuntime @ RefreshUtils.js:243
$ReactRefreshModuleRuntime$ @ app.tsx:10
./src/app.tsx @ app.tsx:10
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
_requireSelf @ hot module replacement:102
apply @ jsonp chunk loading:407
(anonymous) @ hot module replacement:344
internalApply @ hot module replacement:342
(anonymous) @ hot module replacement:279
waitForBlockingPromises @ hot module replacement:233
(anonymous) @ hot module replacement:277
Promise.then (async)
(anonymous) @ hot module replacement:276
Promise.then (async)
(anonymous) @ hot module replacement:256
Promise.then (async)
hotCheck @ hot module replacement:247
check @ dev-server.js:13
(anonymous) @ dev-server.js:68
emit @ events.js:153
reloadApp @ reloadApp.js:46
warnings @ index.js:261
(anonymous) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
draco_decoder_nodejs.js:24 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -sASSERTIONS for more info.
    at f (draco_decoder_nodejs.js:24:1)
    at draco_decoder_nodejs.js:38:1

```

**Comment by FrankGalligan** [comment]
Hi what happens when you run this https://github.com/google/draco/blob/master/javascript/npm/draco3d/draco_minimal_encoder_example.js?
